namespace Dash
{
    public enum DashButtons
    {
        BtnWarning,
        BtnInfo,
        BtnPrimary,
        BtnLink
    }

    public enum DashIcons
    {
        ArrowsCw,
        BellAlt,
        Bug,
        Calendar,
        Cancel,
        ChartBar,
        Clone,
        Corner,
        Database,
        Down,
        Edit,
        EmoUnhappy,
        Fire,
        Heartbeat,
        Help,
        Home,
        Info,
        Key,
        Lamp,
        ListAlt,
        ListBullet,
        ListNumbered,
        Login,
        Logout,
        Max,
        Menu,
        Min,
        Minus,
        Move,
        Pencil,
        Plus,
        Search,
        Sort,
        SortDown,
        SortUp,
        Th,
        ToEnd,
        ToEndAlt,
        ToStart,
        ToStartAlt,
        Trash,
        Unlock,
        Up,
        User,
        Users
    }

    public enum HttpVerbs
    {
        Get,
        Put,
        Post,
        Delete
    }

    public enum DataToggles
    {
        Alertify,
        Autocomplete,
        Chart,
        ChartExport,
        CollapsibleList,
        Colorpicker,
        ColumnSelector,
        ContentReplace,
        ContextHelp,
        Dashboard,
        Datepicker,
        Disable,
        Dotable,
        Dropdown,
        Hide,
        InputReplace,
        NavMenu,
        Tab,
        TagList,
        Widget
    }
}
