//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dash.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Permissions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Permissions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dash.I18n.Permissions", typeof(Permissions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ControllerActions {
            get {
                return ResourceManager.GetString("ControllerActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the common permissions needed for a controller easily.  Enter the controller name, then check the box for each permission you want to create..
        /// </summary>
        public static string ControllerExplain {
            get {
                return ResourceManager.GetString("ControllerExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Controller.
        /// </summary>
        public static string CreateController {
            get {
                return ResourceManager.GetString("CreateController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Permission.
        /// </summary>
        public static string CreatePermission {
            get {
                return ResourceManager.GetString("CreatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Permission.
        /// </summary>
        public static string EditPermission {
            get {
                return ResourceManager.GetString("EditPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A permission for this controller/action combo already exists..
        /// </summary>
        public static string ErrorDuplicateName {
            get {
                return ResourceManager.GetString("ErrorDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a controller name and select at least one action..
        /// </summary>
        public static string ErrorSelectAction {
            get {
                return ResourceManager.GetString("ErrorSelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string MenuItem {
            get {
                return ResourceManager.GetString("MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permission.
        /// </summary>
        public static string PermissionLower {
            get {
                return ResourceManager.GetString("PermissionLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The permission(s) were created successfully..
        /// </summary>
        public static string SuccessCreatingController {
            get {
                return ResourceManager.GetString("SuccessCreatingController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission deleted successfully..
        /// </summary>
        public static string SuccessDeletingPermission {
            get {
                return ResourceManager.GetString("SuccessDeletingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission saved successfully..
        /// </summary>
        public static string SuccessSavingPermission {
            get {
                return ResourceManager.GetString("SuccessSavingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Permissions.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
    }
}
