//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dash.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dash.Resources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was updated successfully. You will need to refresh this page if you changed your language..
        /// </summary>
        public static string AccountUpdated {
            get {
                return ResourceManager.GetString("AccountUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string AuthCode {
            get {
                return ResourceManager.GetString("AuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to change your password. New passwords are required to be a minimum of {0} characters in length..
        /// </summary>
        public static string ChangePasswordText {
            get {
                return ResourceManager.GetString("ChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;A request to reset your password was received.  You can reset your password &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;. This link is only valid for 15 minutes.&lt;/p&gt;&lt;p&gt;If you did not request this, you can ignore this email.&lt;/p&gt;.
        /// </summary>
        public static string EmailTextPasswordReset {
            get {
                return ResourceManager.GetString("EmailTextPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash Password Reset Request.
        /// </summary>
        public static string EmailTitlePasswordReset {
            get {
                return ResourceManager.GetString("EmailTitlePasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked for {0} minutes because of too many failed login attempts..
        /// </summary>
        public static string ErrorAccountLocked {
            get {
                return ResourceManager.GetString("ErrorAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user information you entered is valid but you don&apos;t have access to this site..
        /// </summary>
        public static string ErrorCannotMatchMembership {
            get {
                return ResourceManager.GetString("ErrorCannotMatchMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the username/password you entered..
        /// </summary>
        public static string ErrorCannotValidate {
            get {
                return ResourceManager.GetString("ErrorCannotValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user name for that email address already exists. Please enter a different email address..
        /// </summary>
        public static string ErrorDuplicateEmail {
            get {
                return ResourceManager.GetString("ErrorDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name..
        /// </summary>
        public static string ErrorDuplicateUserName {
            get {
                return ResourceManager.GetString("ErrorDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two factor authentication must be completed within five minutes. Please try logging in again..
        /// </summary>
        public static string ErrorFactorExpired {
            get {
                return ResourceManager.GetString("ErrorFactorExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code you entered was not correct..
        /// </summary>
        public static string ErrorFactorInvalid {
            get {
                return ResourceManager.GetString("ErrorFactorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string ErrorInvalidAnswer {
            get {
                return ResourceManager.GetString("ErrorInvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string ErrorInvalidEmail {
            get {
                return ResourceManager.GetString("ErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Passwords must be at least 6 characters long, with at least one non-alphanumeric character..
        /// </summary>
        public static string ErrorInvalidPassword {
            get {
                return ResourceManager.GetString("ErrorInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string ErrorInvalidQuestion {
            get {
                return ResourceManager.GetString("ErrorInvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user could not be found..
        /// </summary>
        public static string ErrorInvalidUser {
            get {
                return ResourceManager.GetString("ErrorInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string ErrorInvalidUserName {
            get {
                return ResourceManager.GetString("ErrorInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password you entered is not correct..
        /// </summary>
        public static string ErrorOldPassword {
            get {
                return ResourceManager.GetString("ErrorOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ErrorPasswordMatch {
            get {
                return ResourceManager.GetString("ErrorPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string ErrorProviderError {
            get {
                return ResourceManager.GetString("ErrorProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset link you clicked has expired or is invalid. Please try again..
        /// </summary>
        public static string ErrorResetPassword {
            get {
                return ResourceManager.GetString("ErrorResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred saving the password..
        /// </summary>
        public static string ErrorSavingPassword {
            get {
                return ResourceManager.GetString("ErrorSavingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred sending the email..
        /// </summary>
        public static string ErrorSendingEmail {
            get {
                return ResourceManager.GetString("ErrorSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string ErrorUserRejected {
            get {
                return ResourceManager.GetString("ErrorUserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To configure two factor authentication, you will need to install Google Authenticator on your mobile device. Once installed, use it to scan the QR code below.  Then click `Done` to try logging in again..
        /// </summary>
        public static string FactorText {
            get {
                return ResourceManager.GetString("FactorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A link to reset the password for this account has been sent to the associated email address..
        /// </summary>
        public static string ForgotPasswordEmailSentText {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;ve forgotten your password, a link to create a new one can be sent to the email address for your account. Just enter your username and click the `Send Email` button below. .
        /// </summary>
        public static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string PasswordChangedText {
            get {
                return ResourceManager.GetString("PasswordChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to reset your password. Passwords must be at least 6 characters long, with at least one non-alphanumeric character..
        /// </summary>
        public static string ResetPasswordText {
            get {
                return ResourceManager.GetString("ResetPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor Authentication.
        /// </summary>
        public static string TwoFactor {
            get {
                return ResourceManager.GetString("TwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Account.
        /// </summary>
        public static string UpdateAccount {
            get {
                return ResourceManager.GetString("UpdateAccount", resourceCulture);
            }
        }
    }
}
