//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dash.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Alerts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Alerts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dash.Resources.Alerts", typeof(Alerts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert.
        /// </summary>
        public static string AlertLower {
            get {
                return ResourceManager.GetString("AlertLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name for the new alert..
        /// </summary>
        public static string CopyBody {
            get {
                return ResourceManager.GetString("CopyBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Alert.
        /// </summary>
        public static string CreateAlert {
            get {
                return ResourceManager.GetString("CreateAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Of Month.
        /// </summary>
        public static string CronDayOfMonth {
            get {
                return ResourceManager.GetString("CronDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Of Week.
        /// </summary>
        public static string CronDayOfWeek {
            get {
                return ResourceManager.GetString("CronDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string CronHour {
            get {
                return ResourceManager.GetString("CronHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string CronMinute {
            get {
                return ResourceManager.GetString("CronMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string CronMonth {
            get {
                return ResourceManager.GetString("CronMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Alert.
        /// </summary>
        public static string EditAlert {
            get {
                return ResourceManager.GetString("EditAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron day of month must be a `*` or a number between 1 and 31..
        /// </summary>
        public static string ErrorCronDayOfMonth {
            get {
                return ResourceManager.GetString("ErrorCronDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron day of week must be a `*` or a number between 0 and 6..
        /// </summary>
        public static string ErrorCronDayOfWeek {
            get {
                return ResourceManager.GetString("ErrorCronDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron hour must be a `*` or a number between 0 and 23..
        /// </summary>
        public static string ErrorCronHour {
            get {
                return ResourceManager.GetString("ErrorCronHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron minute must be a `*` or a number between 0 and 59..
        /// </summary>
        public static string ErrorCronMinute {
            get {
                return ResourceManager.GetString("ErrorCronMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron month must be a `*` or a number between 1 and 12..
        /// </summary>
        public static string ErrorCronMonth {
            get {
                return ResourceManager.GetString("ErrorCronMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron expression is not valid..
        /// </summary>
        public static string ErrorCronParse {
            get {
                return ResourceManager.GetString("ErrorCronParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An alert named `{0}` has the same criteria. Criteria cannot be duplicated..
        /// </summary>
        public static string ErrorHash {
            get {
                return ResourceManager.GetString("ErrorHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name is required to create an alert..
        /// </summary>
        public static string ErrorNameRequired {
            get {
                return ResourceManager.GetString("ErrorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Notification Date.
        /// </summary>
        public static string LastNotificationDate {
            get {
                return ResourceManager.GetString("LastNotificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Run Date.
        /// </summary>
        public static string LastRunDate {
            get {
                return ResourceManager.GetString("LastRunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string MenuItem {
            get {
                return ResourceManager.GetString("MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Interval.
        /// </summary>
        public static string NotificationInterval {
            get {
                return ResourceManager.GetString("NotificationInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Count.
        /// </summary>
        public static string ResultCount {
            get {
                return ResourceManager.GetString("ResultCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To.
        /// </summary>
        public static string SendTo {
            get {
                return ResourceManager.GetString("SendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert copied successfully..
        /// </summary>
        public static string SuccessCopyingAlert {
            get {
                return ResourceManager.GetString("SuccessCopyingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert deleted successfully..
        /// </summary>
        public static string SuccessDeletingAlert {
            get {
                return ResourceManager.GetString("SuccessDeletingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert saved successfully..
        /// </summary>
        public static string SuccessSavingAlert {
            get {
                return ResourceManager.GetString("SuccessSavingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Alerts.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
    }
}
