//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dash.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Charts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Charts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dash.Resources.Charts", typeof(Charts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregator.
        /// </summary>
        public static string Aggregator {
            get {
                return ResourceManager.GetString("Aggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Chart Type.
        /// </summary>
        public static string ChangeType {
            get {
                return ResourceManager.GetString("ChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this chart? This will also delete any widgets using this chart..
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Chart.
        /// </summary>
        public static string CopyChart {
            get {
                return ResourceManager.GetString("CopyChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Chart.
        /// </summary>
        public static string CreateChart {
            get {
                return ResourceManager.GetString("CreateChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Interval.
        /// </summary>
        public static string DateInterval {
            get {
                return ResourceManager.GetString("DateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart was modified by the owner. You should close the chart and re-open it to see the latest version..
        /// </summary>
        public static string ErrorChartModified {
            get {
                return ResourceManager.GetString("ErrorChartModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred querying the database. Check your reports. Or, try reloading the page..
        /// </summary>
        public static string ErrorGettingData {
            get {
                return ResourceManager.GetString("ErrorGettingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string ErrorNameRequired {
            get {
                return ResourceManager.GetString("ErrorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the chart ranges returned any data. Try modifying the ranges or the underlying reports..
        /// </summary>
        public static string ErrorNoData {
            get {
                return ResourceManager.GetString("ErrorNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to add at least one range before you can view the chart..
        /// </summary>
        public static string ErrorNoRanges {
            get {
                return ResourceManager.GetString("ErrorNoRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the owner of the chart is allowed to do this..
        /// </summary>
        public static string ErrorOwnerOnly {
            get {
                return ResourceManager.GetString("ErrorOwnerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view the requested chart..
        /// </summary>
        public static string ErrorPermissionDenied {
            get {
                return ResourceManager.GetString("ErrorPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart type is required..
        /// </summary>
        public static string ErrorTypeRequired {
            get {
                return ResourceManager.GetString("ErrorTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Data.
        /// </summary>
        public static string ExportChartData {
            get {
                return ResourceManager.GetString("ExportChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Name.
        /// </summary>
        public static string ExportChartName {
            get {
                return ResourceManager.GetString("ExportChartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Width.
        /// </summary>
        public static string ExportChartWidth {
            get {
                return ResourceManager.GetString("ExportChartWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string LabelAggregator_Avg {
            get {
                return ResourceManager.GetString("LabelAggregator_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string LabelAggregator_Count {
            get {
                return ResourceManager.GetString("LabelAggregator_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string LabelAggregator_Max {
            get {
                return ResourceManager.GetString("LabelAggregator_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string LabelAggregator_Min {
            get {
                return ResourceManager.GetString("LabelAggregator_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string LabelAggregator_Sum {
            get {
                return ResourceManager.GetString("LabelAggregator_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        public static string LabelType_Bar {
            get {
                return ResourceManager.GetString("LabelType_Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doughnut.
        /// </summary>
        public static string LabelType_Doughnut {
            get {
                return ResourceManager.GetString("LabelType_Doughnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Bar.
        /// </summary>
        public static string LabelType_HorizontalBar {
            get {
                return ResourceManager.GetString("LabelType_HorizontalBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string LabelType_Line {
            get {
                return ResourceManager.GetString("LabelType_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie.
        /// </summary>
        public static string LabelType_Pie {
            get {
                return ResourceManager.GetString("LabelType_Pie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string MenuItem {
            get {
                return ResourceManager.GetString("MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart name was updated..
        /// </summary>
        public static string NameSaved {
            get {
                return ResourceManager.GetString("NameSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name for the chart..
        /// </summary>
        public static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranges.
        /// </summary>
        public static string Ranges {
            get {
                return ResourceManager.GetString("Ranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Chart.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Color.
        /// </summary>
        public static string SelectColor {
            get {
                return ResourceManager.GetString("SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Chart.
        /// </summary>
        public static string ShareChart {
            get {
                return ResourceManager.GetString("ShareChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add users or roles to share this chart with. These users can view the chart, but only the chart owner can make changes. If you share a chart with a user, they will also be able to see the reports the chart uses..
        /// </summary>
        public static string ShareExplain {
            get {
                return ResourceManager.GetString("ShareExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart copied successfully..
        /// </summary>
        public static string SuccessCopyingChart {
            get {
                return ResourceManager.GetString("SuccessCopyingChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart deleted successfully..
        /// </summary>
        public static string SuccessDeletingChart {
            get {
                return ResourceManager.GetString("SuccessDeletingChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart saved successfully..
        /// </summary>
        public static string SuccessSavingChart {
            get {
                return ResourceManager.GetString("SuccessSavingChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Charts.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Chart.
        /// </summary>
        public static string ViewChart {
            get {
                return ResourceManager.GetString("ViewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Axis.
        /// </summary>
        public static string XAxisColumn {
            get {
                return ResourceManager.GetString("XAxisColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-Axis.
        /// </summary>
        public static string YAxisColumn {
            get {
                return ResourceManager.GetString("YAxisColumn", resourceCulture);
            }
        }
    }
}
