//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dash.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Databases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Databases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dash.Resources.Databases", typeof(Databases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Paging.
        /// </summary>
        public static string AllowPaging {
            get {
                return ResourceManager.GetString("AllowPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String.
        /// </summary>
        public static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Database.
        /// </summary>
        public static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database.
        /// </summary>
        public static string DatabaseLower {
            get {
                return ResourceManager.GetString("DatabaseLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Database.
        /// </summary>
        public static string EditDatabase {
            get {
                return ResourceManager.GetString("EditDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database with this name already exists..
        /// </summary>
        public static string ErrorDuplicateName {
            get {
                return ResourceManager.GetString("ErrorDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match..
        /// </summary>
        public static string ErrorPasswordMatching {
            get {
                return ResourceManager.GetString("ErrorPasswordMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a username to connect to the database as, or a connection string..
        /// </summary>
        public static string ErrorUsernameRequired {
            get {
                return ResourceManager.GetString("ErrorUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Password.
        /// </summary>
        public static string IsEmptyPassword {
            get {
                return ResourceManager.GetString("IsEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySql.
        /// </summary>
        public static string LabelType_MySql {
            get {
                return ResourceManager.GetString("LabelType_MySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql Server.
        /// </summary>
        public static string LabelType_SqlServer {
            get {
                return ResourceManager.GetString("LabelType_SqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        public static string MenuItem {
            get {
                return ResourceManager.GetString("MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database deleted successfully..
        /// </summary>
        public static string SuccessDeletingDatabase {
            get {
                return ResourceManager.GetString("SuccessDeletingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database saved successfully..
        /// </summary>
        public static string SuccessSavingDatabase {
            get {
                return ResourceManager.GetString("SuccessSavingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection test succeeded..
        /// </summary>
        public static string SuccessTestingConnection {
            get {
                return ResourceManager.GetString("SuccessTestingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Databases.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
    }
}
