//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dash.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Filters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Filters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dash.Resources.Filters", typeof(Filters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string LabelDateInterval_Day {
            get {
                return ResourceManager.GetString("LabelDateInterval_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Minutes.
        /// </summary>
        public static string LabelDateInterval_FifteenMinutes {
            get {
                return ResourceManager.GetString("LabelDateInterval_FifteenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Minutes.
        /// </summary>
        public static string LabelDateInterval_FiveMinutes {
            get {
                return ResourceManager.GetString("LabelDateInterval_FiveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string LabelDateInterval_Hour {
            get {
                return ResourceManager.GetString("LabelDateInterval_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string LabelDateInterval_Month {
            get {
                return ResourceManager.GetString("LabelDateInterval_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string LabelDateInterval_None {
            get {
                return ResourceManager.GetString("LabelDateInterval_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Minute.
        /// </summary>
        public static string LabelDateInterval_OneMinute {
            get {
                return ResourceManager.GetString("LabelDateInterval_OneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        public static string LabelDateInterval_Quarter {
            get {
                return ResourceManager.GetString("LabelDateInterval_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Minutes.
        /// </summary>
        public static string LabelDateInterval_TenMinutes {
            get {
                return ResourceManager.GetString("LabelDateInterval_TenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Minutes.
        /// </summary>
        public static string LabelDateInterval_ThirtyMinutes {
            get {
                return ResourceManager.GetString("LabelDateInterval_ThirtyMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string LabelDateInterval_Week {
            get {
                return ResourceManager.GetString("LabelDateInterval_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string LabelDateInterval_Year {
            get {
                return ResourceManager.GetString("LabelDateInterval_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        public static string LabelDateRange_LastMonth {
            get {
                return ResourceManager.GetString("LabelDateRange_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Quarter.
        /// </summary>
        public static string LabelDateRange_LastQuarter {
            get {
                return ResourceManager.GetString("LabelDateRange_LastQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        public static string LabelDateRange_LastWeek {
            get {
                return ResourceManager.GetString("LabelDateRange_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        public static string LabelDateRange_LastYear {
            get {
                return ResourceManager.GetString("LabelDateRange_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string LabelDateRange_ThisMonth {
            get {
                return ResourceManager.GetString("LabelDateRange_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Quarter.
        /// </summary>
        public static string LabelDateRange_ThisQuarter {
            get {
                return ResourceManager.GetString("LabelDateRange_ThisQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string LabelDateRange_ThisWeek {
            get {
                return ResourceManager.GetString("LabelDateRange_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        public static string LabelDateRange_ThisYear {
            get {
                return ResourceManager.GetString("LabelDateRange_ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string LabelDateRange_Today {
            get {
                return ResourceManager.GetString("LabelDateRange_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string LabelDateRange_Yesterday {
            get {
                return ResourceManager.GetString("LabelDateRange_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Interval.
        /// </summary>
        public static string LabelFilter_DateInterval {
            get {
                return ResourceManager.GetString("LabelFilter_DateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string LabelFilter_Equal {
            get {
                return ResourceManager.GetString("LabelFilter_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string LabelFilter_GreaterThan {
            get {
                return ResourceManager.GetString("LabelFilter_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        public static string LabelFilter_GreaterThanEqualTo {
            get {
                return ResourceManager.GetString("LabelFilter_GreaterThanEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string LabelFilter_In {
            get {
                return ResourceManager.GetString("LabelFilter_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string LabelFilter_LessThan {
            get {
                return ResourceManager.GetString("LabelFilter_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        public static string LabelFilter_LessThanEqualTo {
            get {
                return ResourceManager.GetString("LabelFilter_LessThanEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string LabelFilter_Like {
            get {
                return ResourceManager.GetString("LabelFilter_Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !=.
        /// </summary>
        public static string LabelFilter_NotEqual {
            get {
                return ResourceManager.GetString("LabelFilter_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not In.
        /// </summary>
        public static string LabelFilter_NotIn {
            get {
                return ResourceManager.GetString("LabelFilter_NotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Like.
        /// </summary>
        public static string LabelFilter_NotLike {
            get {
                return ResourceManager.GetString("LabelFilter_NotLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        public static string LabelFilter_Range {
            get {
                return ResourceManager.GetString("LabelFilter_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string LabelGroup_Avg {
            get {
                return ResourceManager.GetString("LabelGroup_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string LabelGroup_Count {
            get {
                return ResourceManager.GetString("LabelGroup_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string LabelGroup_Max {
            get {
                return ResourceManager.GetString("LabelGroup_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string LabelGroup_Min {
            get {
                return ResourceManager.GetString("LabelGroup_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string LabelGroup_Sum {
            get {
                return ResourceManager.GetString("LabelGroup_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary.
        /// </summary>
        public static string LabelType_Binary {
            get {
                return ResourceManager.GetString("LabelType_Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        public static string LabelType_Boolean {
            get {
                return ResourceManager.GetString("LabelType_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LabelType_Date {
            get {
                return ResourceManager.GetString("LabelType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        public static string LabelType_Numeric {
            get {
                return ResourceManager.GetString("LabelType_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string LabelType_Select {
            get {
                return ResourceManager.GetString("LabelType_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string LabelType_Text {
            get {
                return ResourceManager.GetString("LabelType_Text", resourceCulture);
            }
        }
    }
}
