//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dash.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dash.Resources.Reports", typeof(Reports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this report? This will also delete any chart ranges or widgets using this report..
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this filter?.
        /// </summary>
        public static string ConfirmDeleteFilter {
            get {
                return ResourceManager.GetString("ConfirmDeleteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this group?.
        /// </summary>
        public static string ConfirmDeleteGroup {
            get {
                return ResourceManager.GetString("ConfirmDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this share?.
        /// </summary>
        public static string ConfirmDeleteShare {
            get {
                return ResourceManager.GetString("ConfirmDeleteShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Query.
        /// </summary>
        public static string CountQuery {
            get {
                return ResourceManager.GetString("CountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Filter.
        /// </summary>
        public static string CreateFilter {
            get {
                return ResourceManager.GetString("CreateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Report.
        /// </summary>
        public static string CreateReport {
            get {
                return ResourceManager.GetString("CreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Share.
        /// </summary>
        public static string CreateShare {
            get {
                return ResourceManager.GetString("CreateShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Query.
        /// </summary>
        public static string DataQuery {
            get {
                return ResourceManager.GetString("DataQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset.
        /// </summary>
        public static string Dataset {
            get {
                return ResourceManager.GetString("Dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Filter.
        /// </summary>
        public static string EditFilter {
            get {
                return ResourceManager.GetString("EditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Group.
        /// </summary>
        public static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Share.
        /// </summary>
        public static string EditShare {
            get {
                return ResourceManager.GetString("EditShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This filter is already first..
        /// </summary>
        public static string ErrorAlreadyFirstFilter {
            get {
                return ResourceManager.GetString("ErrorAlreadyFirstFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group is already first..
        /// </summary>
        public static string ErrorAlreadyFirstGroup {
            get {
                return ResourceManager.GetString("ErrorAlreadyFirstGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This filter is already last..
        /// </summary>
        public static string ErrorAlreadyLastFilter {
            get {
                return ResourceManager.GetString("ErrorAlreadyLastFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group is already last..
        /// </summary>
        public static string ErrorAlreadyLastGroup {
            get {
                return ResourceManager.GetString("ErrorAlreadyLastGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Try reloading the page..
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred querying the database. Check your filters. Or, try reloading the page..
        /// </summary>
        public static string ErrorGettingData {
            get {
                return ResourceManager.GetString("ErrorGettingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dataset Id..
        /// </summary>
        public static string ErrorInvalidDatasetId {
            get {
                return ResourceManager.GetString("ErrorInvalidDatasetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid report Id..
        /// </summary>
        public static string ErrorInvalidReportId {
            get {
                return ResourceManager.GetString("ErrorInvalidReportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name is required to create the report..
        /// </summary>
        public static string ErrorNameRequired {
            get {
                return ResourceManager.GetString("ErrorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no columns available for this report..
        /// </summary>
        public static string ErrorNoColumnsSelected {
            get {
                return ResourceManager.GetString("ErrorNoColumnsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no columns selected for this report. Use `Columns` from the menu to select columns..
        /// </summary>
        public static string ErrorNoColumnsSelectedChange {
            get {
                return ResourceManager.GetString("ErrorNoColumnsSelectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This dataset doesn&apos;t have any columns you can filter on..
        /// </summary>
        public static string ErrorNoFilterColumns {
            get {
                return ResourceManager.GetString("ErrorNoFilterColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This dataset doesn&apos;t have any columns you can group on..
        /// </summary>
        public static string ErrorNoGroupColumns {
            get {
                return ResourceManager.GetString("ErrorNoGroupColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This dataset uses a stored procedure which has no parameters that can be used to create filters..
        /// </summary>
        public static string ErrorNoProcParams {
            get {
                return ResourceManager.GetString("ErrorNoProcParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the owner of the report is allowed to do this..
        /// </summary>
        public static string ErrorOwnerOnly {
            get {
                return ResourceManager.GetString("ErrorOwnerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view the requested report..
        /// </summary>
        public static string ErrorPermissionDenied {
            get {
                return ResourceManager.GetString("ErrorPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Criteria is required when using the Between operator..
        /// </summary>
        public static string ErrorRangeCriteria {
            get {
                return ResourceManager.GetString("ErrorRangeCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the data source. Check with the user who created the data source..
        /// </summary>
        public static string ErrorReportDatasetAccess {
            get {
                return ResourceManager.GetString("ErrorReportDatasetAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one column..
        /// </summary>
        public static string ErrorSelectColumn {
            get {
                return ResourceManager.GetString("ErrorSelectColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string FilterColumn {
            get {
                return ResourceManager.GetString("FilterColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria Value.
        /// </summary>
        public static string FilterCriteria {
            get {
                return ResourceManager.GetString("FilterCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Criteria.
        /// </summary>
        public static string FilterCriteria2 {
            get {
                return ResourceManager.GetString("FilterCriteria2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string FilterOperator {
            get {
                return ResourceManager.GetString("FilterOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string GroupColumn {
            get {
                return ResourceManager.GetString("GroupColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string MenuItem {
            get {
                return ResourceManager.GetString("MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name for the report..
        /// </summary>
        public static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string SelectColumns {
            get {
                return ResourceManager.GetString("SelectColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag columns left or right to select or unselect them. Drag columns up and down to reorder..
        /// </summary>
        public static string SelectColumnsExplain {
            get {
                return ResourceManager.GetString("SelectColumnsExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareReport {
            get {
                return ResourceManager.GetString("ShareReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report copied successfully..
        /// </summary>
        public static string SuccessCopyingReport {
            get {
                return ResourceManager.GetString("SuccessCopyingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report created successfully. Select columns now to get started..
        /// </summary>
        public static string SuccessCreatingReport {
            get {
                return ResourceManager.GetString("SuccessCreatingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter deleted successfully..
        /// </summary>
        public static string SuccessDeletingFilter {
            get {
                return ResourceManager.GetString("SuccessDeletingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group deleted successfully..
        /// </summary>
        public static string SuccessDeletingGroup {
            get {
                return ResourceManager.GetString("SuccessDeletingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report deleted successfully..
        /// </summary>
        public static string SuccessDeletingReport {
            get {
                return ResourceManager.GetString("SuccessDeletingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share deleted successfully..
        /// </summary>
        public static string SuccessDeletingShare {
            get {
                return ResourceManager.GetString("SuccessDeletingShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter saved successfully..
        /// </summary>
        public static string SuccessSavingFilter {
            get {
                return ResourceManager.GetString("SuccessSavingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group saved successfully..
        /// </summary>
        public static string SuccessSavingGroup {
            get {
                return ResourceManager.GetString("SuccessSavingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report saved successfully..
        /// </summary>
        public static string SuccessSavingReport {
            get {
                return ResourceManager.GetString("SuccessSavingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share saved successfully..
        /// </summary>
        public static string SuccessSavingShare {
            get {
                return ResourceManager.GetString("SuccessSavingShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Reports.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Report.
        /// </summary>
        public static string ViewReport {
            get {
                return ResourceManager.GetString("ViewReport", resourceCulture);
            }
        }
    }
}
