//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dash.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Widgets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Widgets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dash.Resources.Widgets", typeof(Widgets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Widget.
        /// </summary>
        public static string CreateWidget {
            get {
                return ResourceManager.GetString("CreateWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Widget.
        /// </summary>
        public static string DeleteWidget {
            get {
                return ResourceManager.GetString("DeleteWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Widget.
        /// </summary>
        public static string EditWidget {
            get {
                return ResourceManager.GetString("EditWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a report or a chart for this widget to display..
        /// </summary>
        public static string ErrorReportOrChartRequired {
            get {
                return ResourceManager.GetString("ErrorReportOrChartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Minutes.
        /// </summary>
        public static string LabelRefreshRate_FifteenMinutes {
            get {
                return ResourceManager.GetString("LabelRefreshRate_FifteenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Minutes.
        /// </summary>
        public static string LabelRefreshRate_FiveMinutes {
            get {
                return ResourceManager.GetString("LabelRefreshRate_FiveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string LabelRefreshRate_Never {
            get {
                return ResourceManager.GetString("LabelRefreshRate_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Hour.
        /// </summary>
        public static string LabelRefreshRate_OneHour {
            get {
                return ResourceManager.GetString("LabelRefreshRate_OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Minute.
        /// </summary>
        public static string LabelRefreshRate_OneMinute {
            get {
                return ResourceManager.GetString("LabelRefreshRate_OneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Minutes.
        /// </summary>
        public static string LabelRefreshRate_TenMinutes {
            get {
                return ResourceManager.GetString("LabelRefreshRate_TenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Minutes.
        /// </summary>
        public static string LabelRefreshRate_ThirtyMinutes {
            get {
                return ResourceManager.GetString("LabelRefreshRate_ThirtyMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Seconds.
        /// </summary>
        public static string LabelRefreshRate_ThirtySeconds {
            get {
                return ResourceManager.GetString("LabelRefreshRate_ThirtySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Widget.
        /// </summary>
        public static string LinkAdd {
            get {
                return ResourceManager.GetString("LinkAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Rate.
        /// </summary>
        public static string RefreshRate {
            get {
                return ResourceManager.GetString("RefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget saved successfully..
        /// </summary>
        public static string SuccessSavingWidget {
            get {
                return ResourceManager.GetString("SuccessSavingWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Full Screen.
        /// </summary>
        public static string ToggleFullScreen {
            get {
                return ResourceManager.GetString("ToggleFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Chart.
        /// </summary>
        public static string ViewChart {
            get {
                return ResourceManager.GetString("ViewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Report.
        /// </summary>
        public static string ViewReport {
            get {
                return ResourceManager.GetString("ViewReport", resourceCulture);
            }
        }
    }
}
